### ISSUE TITLE
Add search filter for ISI Journal

### ISSUE THREAD

**Issue by alanorth** [ilri/AReS#12]
CGSpace has a field called "Journal status" (`cg.isijournal`) that indicates a journal is high impact. We would like a search filter for this. The text value, if present, is always "ISI Journal".

**Comment by moayadnajd** [comment]
@alanorth please review

**Comment by alanorth** [comment]
Added yesterday. Waiting for new harvest for the values to show up. The search filter is in the sidebar.

![Screenshot_2020-07-23 OpenRXV(16)-fs8](https://user-images.githubusercontent.com/191754/88259966-153dfc80-cccc-11ea-93e4-07438f6af69f.png)
