### ISSUE TITLE
Add "review status" to search filters

### ISSUE THREAD

**Issue by alanorth** [ilri/AReS#4]
In CGSpace the review status field contains values like "Internal Review" and "Peer Review" to indicate the level of review an item has had. The field used for this is currently `dc.description.version`, but in CG Core v2 it will likely change to `cg.peer-reviewed` (remember to check the latest [cg-core schema](https://agriculturalsemantics.github.io/cg-core/cgcore.html)).

**Comment by moayadnajd** [comment]
@alanorth please review

**Comment by alanorth** [comment]
Review status added to schema mapping and sidebar filters.

![Screenshot_2020-07-23 OpenRXV(17)-fs8](https://user-images.githubusercontent.com/191754/88261476-0dcc2280-cccf-11ea-82d3-b5b10606c191.png)
