### ISSUE TITLE
Add WorldFish Digital Archive to AReS

### ISSUE THREAD

**Issue by alanorth** [ilri/AReS#7]
AReS v1 had the [WorldFish Digital Archive](https://digitalarchive.worldfishcenter.org/) so we should add it to AReS v2 as well.

**Comment by chaudj** [comment]
Hi @alanorth. Can we make this a high priority? We had already shared AReS to our staff and they use it as a reference. We also use it to get altmetric scores and other information for our records.
Thanks!

**Comment by alanorth** [comment]
@chaudj sure I changed the GitHub label. Now the ball is in @moayadnajd's court. :stuck_out_tongue:

**Comment by alanorth** [comment]
Moayad added WorldFish to AReS yesterday. Closing.
